name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v2

    - name: Install packages
      run:  npm install

    - name: Bundle
      run:  npm run build

    - name: Deploy to GitHub Pages
      uses: JasonEtco/upload-pages-artifact@v4
      with:
        Branch: main
        folder: dist